### ISSUE TITLE
Error! token or netlify_token secret is required

### ISSUE THREAD

**Issue by smeierzubiesen** [lucaperret/drone-netlify#1]
Steps tried:
- I have passed the token directly in .drone.yml
- created secrets ```token``` and/or ```netlify_token```

Message remains always as indicated in title.

extract from .drone.yml:
```yaml
- name: netlify-staging
  image: lucap/drone-netlify
  token: 40d36c2fb488ef5ed112e76eea171ed3b0807c164c6251a8e93d5b074ec748a6
  site_id:
    from_secret: site_id
  domain: staging.mzb.company
  secrets: [ netlify_token ]
  when:
    branch:
    - master
  directory: public
---
kind: secret
name: netlify_token
data: vjSKKHdr4N5wIThOdHdZGPIf7vf3AVsV8c+Jnjy5gMxa3qOo/oDFEd/C5D7pEKr2HZnOL+UHEE+1qDxVjlPSY7wYFORSN3+UHGuLrxbpwQtAGiYMS8KOmNRRqpg=
---
kind: secret
name: site_id
data: gGsWUge3fpto4qQoEJvt9vZRv3gUhWPrE1/hmkndZcMqmnoUoFqOGo97P2k/NDf17aJ39NgUakOKXgYGahkNHw==
```

I'm out of ideas on what else to try, any help would be appreciated

**Comment by smeierzubiesen** [comment]
repository to look at full source: https://code.mzb.company/MzB-Solutions/website-v2/src/branch/dev

**Comment by smeierzubiesen** [comment]
drone_agent_trace_logs:

```
drone_agent     | 2020/02/02 13:50:03 [DEBUG] POST http://drone-server:80/rpc/v1/beforeAll
drone_agent     | {
drone_agent     |   "arch": "amd64",
drone_agent     |   "build": 27,
drone_agent     |   "level": "info",
drone_agent     |   "machine": "SAL9000",
drone_agent     |   "msg": "runner: start execution",
drone_agent     |   "os": "linux",
drone_agent     |   "pipeline": "website_build",
drone_agent     |   "repo": "MzB-Solutions/website-v2",
drone_agent     |   "stage": 1,
drone_agent     |   "stage-id": 25,
drone_agent     |   "time": "2020-02-02T13:50:03Z"
drone_agent     | }
...
drone_agent     |   "msg": "runner: execution complete",
drone_agent     |   "os": "linux",
drone_agent     |   "machine": "SAL9000",
drone_agent     |   "time": "2020-02-02T13:53:33Z"
drone_agent     | }
drone_agent     | 2020/02/02 13:53:33 [DEBUG] POST http://drone-server:80/rpc/v1/details
drone_agent     | {
drone_agent     |   "arch": "amd64",
drone_agent     |   "level": "debug",
drone_agent     |   "machine": "SAL9000",
drone_agent     |   "msg": "runner: watch for cancel signal",
drone_agent     |   "os": "linux",
drone_agent     |   "time": "2020-02-02T13:53:33Z"
drone_agent     | }
```

**Comment by smeierzubiesen** [comment]
this is how i got it to work: apologies for the long response time:

``` yaml
- name: netlify-staging
  image: lucap/drone-netlify
  environment:
    JEKYLL_ENV: production
    LC_ALL: C.UTF-8
    JEKYLL_VERSION: 3.8
  settings:
    token:
      from_secret: netlify_token
    site_id:
      from_secret: site_id
    domain: some.domain.com
    path: build
  secrets: [netlify_token,site_id]
  when:
    branch:
    - master
```
